### ISSUE TITLE
executing & finished properties in SDWebImageDownloaderOperation.m

### ISSUE THREAD

**Issue by thefans1** [sylverb/Picture-Map#1]
In initWithRequest:
"_executing" should be changed to "self.executing"
"_finished" should be changed to "self.finished"

Same for setExecuting: and setFinished:

**Comment by sylverb** [comment]
Hello,
it seems that SDWebImage version I'm using is outdated now.
I've updated the project to use cocoapods to get MWPhotoBrowser and it dependencies.

**Comment by predescu** [comment]
Sorry for posting this here because is not related with the project but I wanted to contact @thefans. 
@thefans , can you please send me an email? You can find my address on my github profile. 
Thanks

**Comment by thefans1** [comment]
I got a notification from you. What are you looking for?


________________________________

**Comment by predescu** [comment]
Hi @thefans, 
 I was wondering if you are not using "thefans" github account on your daily activities, maybe you want to give it away because I'm interested. I'm using "the-fans" for some projects and I would prefer to not have the dash sign in it. 
Can you please send me an email to discuss about it? 
constantin.predescu@gmail.com is my address. 

Thank you very much.
